require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "c",
    "lua",
    "vim",
    "vimdoc",
    "javascript",
    "typescript",
    "bash",
    "go",
    "python",
    "sql",
    "yaml",
    "json",
    "terraform",
    "dockerfile",
    "gitignore",
    "git_config",
    "gitcommit",
    "hcl",
    "html",
    "latex",
    "markdown_inline",
    "regex",
    "requirements",
    "sql",
    "toml",
    "xml",
  },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
})
