return {
	"tpope/vim-fugitive",
	"navarasu/onedark.nvim",
	"williamboman/mason.nvim",
	"neovim/nvim-lspconfig",
	"williamboman/mason-lspconfig.nvim",
	"jose-elias-alvarez/null-ls.nvim",
	"hrsh7th/nvim-cmp",
	"hrsh7th/cmp-nvim-lsp",
	"nvim-telescope/telescope.nvim",
	"nvim-treesitter/nvim-treesitter",
	"nvim-treesitter/playground",
	"mbbill/undotree",
	"nvim-lua/plenary.nvim",
}
